# Generated by Django 3.1.5 on 2021-01-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tel', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('email_comp', models.CharField(max_length=30, verbose_name='email компании')),
                ('address_comp', models.CharField(max_length=250, verbose_name='Адрес компании')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
