# Generated by Django 3.1.5 on 2021-01-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='Имя человека, оставившего отзыв')),
                ('full_text', models.TextField(verbose_name='Содержание отзыва')),
                ('image', models.ImageField(upload_to='people/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
